langauge: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sriraj14/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sriraj14/docker-react npm run test -- --coverage