langauge: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sriraj14/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sriraj14/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-102770265362"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"